version: '3.8'

services:
  client:
    build:
      context: ./my-app
    volumes:
      - ./my-app:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://server:5000
    depends_on:
      - server

  server:
    build:
      context: ./Express
    volumes:
      - ./Express:/app
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - PORT=5000
    depends_on:
      - mongo
    command: >
      sh -c "while ! nc -z mongo 27017; do sleep 1; done;
      node server.js"

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: